github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-infrastructure-chart
      useSinglePullRequest: true
    - name: activiti-cloud-full-chart
      useSinglePullRequest: true

